version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
    - echo "Installing Dependencies..."
    - cd lambdafunction
    - pip install -r requirements.txt -t python/ 
    - cd ..
  build: 
    commands:
      - echo "Zipping Feed Service Deployment Package"
      - cd lambdafunction
      - zip -r ../dependency_layer.zip python/
      - rm -rf python/
      - zip -r ../feed_service_build_package.zip lambda_function.py
      - cd ..
  post_build: 
    commands:
      # - echo "Deploying to Lambda Function..."
      # - aws lambda update-function-code --function-name Feed-Service --zip-file fileb://feed_service_build_package.zip
      # - echo "Lambda Deployed"
      # - layer_arn=$(aws lambda publish-layer-version --layer-name feed-service-dependencies --zip-file fileb://dependency_layer.zip --output text --query 'LayerVersionArn')
      # - echo "Layer Created"
      # - aws lambda update-function-configuration --function-name Feed-Service --layers $layer_arn
      # - echo "Layer added"

      - echo "Deploying to Lambda Function..."
      - aws lambda update-function-code --function-name Feed-Service --zip-file fileb://feed_service_build_package.zip
      - echo "Lambda Code Updated"
      - lambda_version=$(aws lambda publish-version --function-name Feed-Service --output text --query 'Version')
      - echo "Lambda Version Created $lambda_version"
      - layer_arn=$(aws lambda publish-layer-version --layer-name feed-service-dependencies --zip-file fileb://dependency_layer.zip --output text --query 'LayerVersionArn')
      - echo "Layer Created"
      - aws lambda update-function-configuration --function-name Feed-Service --layers $layer_arn
      - echo "Layer Added"
      - aws lambda update-alias --function-name Feed-Service --name <alias-name> --function-version $lambda_version
      - echo "Alias Updated to Point to New Version"
